require "bundler/gem_tasks"
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

desc "Run tests"
task :default => :spec

desc "Ejecutar las espectativas de la clase Biblioteca"
task :spec do
  sh "rspec -I. spec/biblioteca_spec.rb"
end

desc "Ejecutar con documentacion"
task :doc do
  sh "rspec -I. spec/biblioteca_spec.rb --format documentation"
end